### ISSUE TITLE
have a bug

### ISSUE THREAD

**Issue by kiaxseventh** [Li-Shang/FaceCapture#1]
when  opening camera have Error 
LogCat Error : 

10-25 00:27:10.182 17316-17316/signalprocess.facecapture I/native: I/jni_face_det.cpp:140 det face size: 0
10-25 00:27:10.182 17316-17316/signalprocess.facecapture I/native: I/jni_face_det.cpp:92 getFaceRet
10-25 00:27:10.182 17316-17316/signalprocess.facecapture D/FaceDetector: no face.
10-25 00:27:10.184 17316-17316/signalprocess.facecapture D/skia: onFlyCompress
10-25 00:27:10.193 17316-17316/signalprocess.facecapture I/native: I/jni_face_det.cpp:128 jniBitmapFaceDet
10-25 00:27:10.193 17316-17316/signalprocess.facecapture I/native: I/jni_bitmap2mat.cpp:29 nBitmapToMat: RGBA_8888 -> CV_8UC4
10-25 00:27:10.195 17316-17316/signalprocess.facecapture I/native: I/detector.h:175 com_tzutalin_dlib_PeopleDet go to det(mat)
10-25 00:27:10.281 17316-17316/signalprocess.facecapture I/native: I/detector.h:184 Dlib HOG face det size : 1
10-25 00:27:10.282 17316-17316/signalprocess.facecapture I/native: I/detector.h:190 face index:0number of parts: 0
10-25 00:27:10.282 17316-17316/signalprocess.facecapture I/native: I/jni_face_det.cpp:140 det face size: 1
10-25 00:27:10.282 17316-17316/signalprocess.facecapture I/native: I/jni_face_det.cpp:92 getFaceRet
10-25 00:27:10.282 17316-17316/signalprocess.facecapture D/AndroidRuntime: Shutting down VM
10-25 00:27:10.283 17316-17316/signalprocess.facecapture E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: signalprocess.facecapture, PID: 17316
                                                                           java.lang.IndexOutOfBoundsException: Index: 36, Size: 0
                                                                               at java.util.ArrayList.get(ArrayList.java:411)
                                                                               at signalprocess.facecapture.FaceDetector.solveFacePose(FaceDetector.java:74)
                                                                               at signalprocess.facecapture.FaceDetector.getLandmarks(FaceDetector.java:64)
                                                                               at signalprocess.facecapture.CameraPreview$FrameCallback.onPreviewFrame(CameraPreview.java:173)
                                                                               at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1133)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
10-25 00:27:21.442 17316-17362/signalprocess.facecapture E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
10-25 00:27:21.448 17316-17362/signalprocess.facecapture W/GLThread: eglSwapBuffers failed: EGL_BAD_NATIVE_WINDOW

**Comment by lawsonsli** [comment]
I'm sorry that I don't have time to fix it. You can try to debug with the output log. 
Maybe the reason is that you didn't put this file(shape_predictor_68_face_landmarks.dat) to sdcard directory.
